services:

  web_agora:
    container_name: web_agora
    image: nginx:latest    
    ports:
      - '8000:80'
    volumes:
      - ./backend/public:/app/public
      - ./backend/:/app
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    restart: always   
    tty: true
    working_dir: /etc/nginx/conf.d/
    networks:
      - agoras

  php-fpm:
    build: ./backend
    volumes:
      - ./backend/:/app:delegated
    restart: always
    working_dir: /app
    links:
      - postgres_agora
    networks:
      - agoras

  frontend:
    container_name: frontend_agora
    build: ./frontend
    networks:
      - agoras
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    working_dir: /app
    depends_on:
      - php-fpm
    restart: always

  postgres_agora:
    container_name: bd_agora
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    tty: true
    environment:
      POSTGRES_DB: agora
      POSTGRES_USER: agora
      POSTGRES_PASSWORD: agorasaude
    volumes:
      - ./backend/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agoras

networks:
  agoras:
    driver: bridge  